{
 "title": "Artifactory Dashboard",
 "tags": [ "Artifactory" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(jfrt_runtime_heap_freememory_bytes, job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jfrt_runtime_heap_freememory_bytes{job=\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "GC - Next GC Run",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jfrt_artifacts_gc_next_run_seconds{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC - Time taken by a GC run",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jfrt_artifacts_gc_duration_seconds{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC - Number of binaries removed by a GC run",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jfrt_artifacts_gc_binaries_total{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC - Binary Size",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jfrt_artifacts_gc_size_cleaned_bytes{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Space reclaimed by a GC run"
    },
    {
     "expr": "jfrt_artifacts_gc_current_size_bytes{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Space occupied by Binaries after a GC run (Only for FULL GC runs)"
    }
   ]
  },
  {
   "title": "Projects Amount",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jfrt_projects_active_total{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jfrt Runtime Heap",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((jfrt_runtime_heap_maxmemory_bytes{instance=\"$instance\", job=\"$job\"})-(jfrt_runtime_heap_freememory_bytes{instance=\"$instance\", job=\"$job\"}))*100/sum(jfrt_runtime_heap_maxmemory_bytes{instance=\"$instance\", job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jfrt DB Connections idle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "jfrt_db_connections_idle_total{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "jfrt_db_connections_min_idle_total{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Min idle"
    }
   ]
  },
  {
   "title": "Jfrt DB Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "jfrt_db_connections_active_total{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "jfrt_db_connections_max_active_total{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Max_active"
    }
   ]
  }
 ]
}