{
 "title": "Artifactory Dashboard",
 "tags": [ "Artifactory" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(jfrt_artifacts_gc_next_run_seconds,job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jfrt_db_connections_active_total,instance)"
    }
   },
   {
    "name": "tcp_instance",
    "label": "tcp_instance",
    "query": {
     "query": "label_values(tcp_port_established,instance)"
    }
   },
   {
    "name": "devices",
    "label": "devices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   },
   {
    "name": "node_instance",
    "label": "node_instance",
    "query": {
     "query": "label_values(node_uname_info,instance)"
    }
   },
   {
    "name": "node_job",
    "label": "node_job",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Basic Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Artifactory Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox-http\"}",
     "legendFormat": "Artifactory"
    }
   ]
  },
  {
   "title": "Artifactory Health Check",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 21, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox-http\"}",
     "legendFormat": "$instance"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node_instance\", job=\"$node_job\", mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node_instance\", job=\"$node_job\"}[$__rate_interval])))) * 100"
    }
   ]
  },
  {
   "title": "Sys Load (5m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5{instance=\"$node_instance\", job=\"$node_job\"}) /  count(count(node_cpu_seconds_total{instance=\"$node_instance\", job=\"$node_job\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Sys Load (15m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (15 min average)",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load15{instance=\"$node_instance\", job=\"$node_job\"}) /  count(count(node_cpu_seconds_total{instance=\"$node_instance\", job=\"$node_job\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$node_instance\", job=\"$node_job\"} * 100) / node_memory_MemTotal_bytes{instance=\"$node_instance\", job=\"$node_job\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$node_instance\", job=\"$node_job\"} - node_boot_time_seconds{instance=\"$node_instance\", job=\"$node_job\"}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$node_instance\", job=\"$node_job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node_instance\", job=\"$node_job\"}"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$node_instance\", job=\"$node_job\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node_instance\",job=\"$node_job\", mode=\"system\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node_instance\",job=\"$node_job\"}[$__rate_interval])))",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node_instance\",job=\"$node_job\", mode=\"user\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node_instance\",job=\"$node_job\"}[$__rate_interval])))",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node_instance\",job=\"$node_job\", mode=\"iowait\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node_instance\",job=\"$node_job\"}[$__rate_interval])))",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node_instance\",job=\"$node_job\", mode=~\".*irq\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node_instance\",job=\"$node_job\"}[$__rate_interval])))",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node_instance\",job=\"$node_job\", mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq'}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node_instance\",job=\"$node_job\"}[$__rate_interval])))",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node_instance\",job=\"$node_job\", mode=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node_instance\",job=\"$node_job\"}[$__rate_interval])))",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node_instance\", job=\"node-monitor\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node_instance\", job=\"$node_job\"} - node_memory_MemFree_bytes{instance=\"$node_instance\", job=\"$node_job\"} - (node_memory_Cached_bytes{instance=\"$node_instance\", job=\"$node_job\"} + node_memory_Buffers_bytes{instance=\"$node_instance\", job=\"$node_job\"} + node_memory_SReclaimable_bytes{instance=\"$node_instance\", job=\"$node_job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$node_instance\", job=\"$node_job\"} + node_memory_Buffers_bytes{instance=\"$node_instance\", job=\"$node_job\"} + node_memory_SReclaimable_bytes{instance=\"$node_instance\", job=\"$node_job\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$node_instance\", job=\"$node_job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$node_instance\", job=\"$node_job\"} - node_memory_SwapFree_bytes{instance=\"$node_instance\", job=\"$node_job\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"$node_instance\",job=\"$node_job\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"$node_instance\",job=\"$node_job\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{instance=\"$node_instance\", job=\"$node_job\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{instance=\"$node_instance\", job=\"$node_job\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{instance=\"$node_instance\", job=\"$node_job\"}",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "timeseries",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$node_instance\", job=\"$node_job\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"$node_instance\", job=\"$node_job\",device!~'rootfs'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "I/O Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=\"$node_instance\", job=\"$node_job\"} [$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "title": "Artifactory Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Artifactory Connections",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tomcat_threads_current_threads{application=\"Artifactory\", instance=\"$instance\", job=\"$job\", name=\"http-nio-8081\"}",
     "legendFormat": "Artifactory Tomcat Threads"
    },
    {
     "expr": "jfrt_db_connections_active_total{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Artifactory DB Connections"
    },
    {
     "expr": "s3_connection_current{instance=\"192.168.139.212:8001\", job=\"artifactory_s3_connections\"}",
     "legendFormat": "Artifactory S3 Connections"
    }
   ]
  },
  {
   "title": "Artifactory Tomcat Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "tomcat_threads_current_threads{application=\"Artifactory\", instance=\"$instance\", job=\"$job\", name=\"http-nio-8081\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "tomcat_threads_config_max_threads{application=\"Artifactory\", instance=\"$instance\", job=\"$job\", name=\"http-nio-8081\"}",
     "legendFormat": "Max_active"
    }
   ]
  },
  {
   "title": "Artifactory DB Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
   "targets": [
    {
     "expr": "jfrt_db_connections_active_total{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "jfrt_db_connections_max_active_total{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Max_active"
    }
   ]
  },
  {
   "title": "S3 Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "expr": "s3_connection_current{instance=\"192.168.139.212:8001\", job=\"artifactory_s3_connections\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "s3_connection_max{instance=\"192.168.139.212:8001\", job=\"artifactory_s3_connections\"}",
     "legendFormat": "Max_active"
    }
   ]
  },
  {
   "title": "TCP Connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "tcp_port_established{job=\"tcp_8081_exporter\", port=\"8081\"}",
     "legendFormat": "tcp_8081_established"
    },
    {
     "expr": "tcp_port_timewait{job=\"tcp_8081_exporter\", port=\"8081\"}",
     "legendFormat": "tcp_8081_timewait"
    },
    {
     "expr": "tcp_port_established{job=\"tcp_8081_exporter\", port=\"8082\"}",
     "legendFormat": "tcp_8082_established"
    },
    {
     "expr": "tcp_port_timewait{job=\"tcp_8081_exporter\", port=\"8082\"}",
     "legendFormat": "tcp_8082_timewait"
    }
   ]
  },
  { "title": "Artifactory Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Current Requests",
   "type": "gauge",
   "description": "Current Requests in 15s",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "artifactory_requests_in_window{instance=\"192.168.139.212:8002\", job=\"artifactory_request_exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Code",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  sum by (code) (\n    increase(artifactory_status_codes_total{instance=\"192.168.139.212:8002\", job=\"artifactory_request_exporter\"}[24h])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Slow Requests",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  sum by (tier) (\n    increase(artifactory_request_duration_seconds{instance=\"192.168.139.212:8002\", job=\"artifactory_request_exporter\"}[24h])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Requests & QPS",
   "type": "timeseries",
   "description": "Current Requests in 15s",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "artifactory_requests_in_window{instance=\"192.168.139.212:8002\", job=\"artifactory_request_exporter\"}",
     "legendFormat": "Current Requests (15s Window)"
    },
    {
     "expr": "rate(artifactory_requests_total{instance=\"192.168.139.212:8002\", job=\"artifactory_request_exporter\"}[1m])",
     "legendFormat": "Average QPS (1m Rate)"
    }
   ]
  },
  {
   "title": "Upload size in 15 seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "artifactory_traffic_bytes{direction=\"upload\", instance=\"192.168.139.212:8002\", job=\"artifactory_request_exporter\"}",
     "legendFormat": "Upload (15s Window)"
    }
   ]
  },
  {
   "title": "Download size in 15 seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "artifactory_traffic_bytes{direction=\"download\", instance=\"192.168.139.212:8002\", job=\"artifactory_request_exporter\"}",
     "legendFormat": "Download (15s Window)"
    }
   ]
  },
  {
   "title": "Artifactory GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC - Next GC Run",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 759 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jfrt_artifacts_gc_next_run_seconds{instance=\"$instance\", job=\"$job\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GC - Time taken by a GC run",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 759 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by(instance, job)(jfrt_artifacts_gc_duration_seconds{instance=\"$instance\", job=\"$job\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GC - Number of binaries removed by a GC run",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 759 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by(instance, job)(jfrt_artifacts_gc_binaries_total{instance=\"$instance\", job=\"$job\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GC - Binary Size",
     "type": "histogram",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 759 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by(instance, job) (\n  jfrt_artifacts_gc_size_cleaned_bytes{instance=\"$instance\", job=\"$job\"}\n)",
       "legendFormat": "Space reclaimed by a GC run"
      },
      {
       "expr": "jfrt_artifacts_gc_current_size_bytes{instance=\"$instance\", job=\"$job\"}",
       "legendFormat": "Space occupied by Binaries after a GC run (Only for FULL GC runs)"
      }
     ]
    },
    {
     "title": "Projects Amount",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 765 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jfrt_projects_active_total{instance=\"$instance\", job=\"$job\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Jfrt Runtime Heap",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 765 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum((jfrt_runtime_heap_maxmemory_bytes{instance=\"$instance\", job=\"$job\"})-(jfrt_runtime_heap_freememory_bytes{instance=\"$instance\", job=\"$job\"}))*100/sum(jfrt_runtime_heap_maxmemory_bytes{instance=\"$instance\", job=\"$job\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}