{
 "title": "Artifactory Dashboard",
 "tags": [ "Artifactory" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(jfrt_runtime_heap_freememory_bytes, job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jfrt_db_connections_active_total,instance)"
    }
   },
   {
    "name": "tcp_instance",
    "label": "tcp_instance",
    "query": {
     "query": "label_values(tcp_port_established,instance)"
    }
   },
   {
    "name": "devices",
    "label": "devices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   }
  ]
 },
 "panels": [
  {
   "title": "Health Check",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "probe_success{instance=\"http://192.168.56.13:8082/artifactory/api/system/ping\", job=\"http-blackbox\"}",
     "legendFormat": "Artifactory 1"
    }
   ]
  },
  { "title": "Basic Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"192.168.56.13:9100\", job=\"node-monitor\", mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"192.168.56.13:9100\", job=\"node-monitor\"}[$__rate_interval])))) * 100"
    }
   ]
  },
  {
   "title": "Sys Load (5m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5{instance=\"192.168.56.13:9100\", job=\"node-monitor\"}) /  count(count(node_cpu_seconds_total{instance=\"192.168.56.13:9100\", job=\"node-monitor\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Sys Load (15m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (15 min average)",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load15{instance=\"192.168.56.13:9100\", job=\"node-monitor\"}) /  count(count(node_cpu_seconds_total{instance=\"192.168.56.13:9100\", job=\"node-monitor\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"192.168.56.13:9100\", job=\"node-monitor\"} * 100) / node_memory_MemTotal_bytes{instance=\"192.168.56.13:9100\", job=\"node-monitor\"})"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"192.168.56.13:9100\", job=\"node-monitor\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"192.168.56.13:9100\", job=\"node-monitor\"}"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"192.168.56.13:9100\", job=\"node-monitor\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"192.168.56.13:9100\", job=\"node-monitor\"} - node_boot_time_seconds{instance=\"192.168.56.13:9100\", job=\"node-monitor\"}"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{instance=\"192.168.56.13:9100\", job=\"node-monitor\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{instance=\"192.168.56.13:9100\", job=\"node-monitor\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{instance=\"192.168.56.13:9100\", job=\"node-monitor\"}",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"192.168.56.13:9100\", job=\"node-monitor\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"192.168.56.13:9100\", job=\"node-monitor\"} - node_memory_MemFree_bytes{instance=\"192.168.56.13:9100\", job=\"node-monitor\"} - (node_memory_Cached_bytes{instance=\"192.168.56.13:9100\", job=\"node-monitor\"} + node_memory_Buffers_bytes{instance=\"192.168.56.13:9100\", job=\"node-monitor\"} + node_memory_SReclaimable_bytes{instance=\"192.168.56.13:9100\", job=\"node-monitor\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"192.168.56.13:9100\", job=\"node-monitor\"} + node_memory_Buffers_bytes{instance=\"192.168.56.13:9100\", job=\"node-monitor\"} + node_memory_SReclaimable_bytes{instance=\"192.168.56.13:9100\", job=\"node-monitor\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"192.168.56.13:9100\", job=\"node-monitor\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"192.168.56.13:9100\", job=\"node-monitor\"} - node_memory_SwapFree_bytes{instance=\"192.168.56.13:9100\", job=\"node-monitor\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "timeseries",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"192.168.56.13:9100\", job=\"node-monitor\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"192.168.56.13:9100\", job=\"node-monitor\",device!~'rootfs'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "I/O Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=\"192.168.56.13:9100\", job=\"node-monitor\"} [$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"192.168.56.13:9100\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"192.168.56.13:9100\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Tomcat threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "tcp_port_established{job=\"tcp_8081_exporter\"}",
     "legendFormat": "tcp_8081_established"
    },
    {
     "expr": "tcp_port_timewait{job=\"tcp_8081_exporter\"}",
     "legendFormat": "tcp_8081_timewait"
    }
   ]
  },
  {
   "title": "DB Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "jfrt_db_connections_active_total{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "jfrt_db_connections_max_active_total{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Max_active"
    }
   ]
  },
  { "title": "Artifactory GC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "GC - Next GC Run",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jfrt_artifacts_gc_next_run_seconds{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC - Time taken by a GC run",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(instance, job)(jfrt_artifacts_gc_duration_seconds{instance=\"$instance\", job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC - Number of binaries removed by a GC run",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(instance, job)(jfrt_artifacts_gc_binaries_total{instance=\"$instance\", job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC - Binary Size",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(instance, job) (\n  jfrt_artifacts_gc_size_cleaned_bytes{instance=\"$instance\", job=\"$job\"}\n)",
     "legendFormat": "Space reclaimed by a GC run"
    },
    {
     "expr": "jfrt_artifacts_gc_current_size_bytes{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Space occupied by Binaries after a GC run (Only for FULL GC runs)"
    }
   ]
  },
  {
   "title": "Projects Amount",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jfrt_projects_active_total{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jfrt Runtime Heap",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((jfrt_runtime_heap_maxmemory_bytes{instance=\"$instance\", job=\"$job\"})-(jfrt_runtime_heap_freememory_bytes{instance=\"$instance\", job=\"$job\"}))*100/sum(jfrt_runtime_heap_maxmemory_bytes{instance=\"$instance\", job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}